/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chiv Ke Eak
 */
import javax.swing.JOptionPane; // use for slide side
import javax.swing.JLabel; // use label class
public class StudentSlide extends javax.swing.JFrame {

    /**
     * Creates new form StudentSlide
     */
    public StudentSlide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntexit = new javax.swing.JLabel();
        bntMinimize = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        quitList = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        showList = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit1.png"))); // NOI18N
        bntexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntexitMouseClicked(evt);
            }
        });
        getContentPane().add(bntexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, -1, -1));

        bntMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/minimize1.png"))); // NOI18N
        bntMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(bntMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, -1, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(0, 153, 153));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quitList.setBackground(new java.awt.Color(0, 153, 153));
        quitList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quitList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/listoff.png"))); // NOI18N
        quitList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitList.setOpaque(true);
        quitList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quitListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quitListMouseExited(evt);
            }
        });
        Menu.add(quitList, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 40, 40));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/directory.png"))); // NOI18N
        jLabel1.setText("Student Directory");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 70));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Info.png"))); // NOI18N
        jLabel2.setText("    Teacher Info");
        jLabel2.setToolTipText("");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 240, 70));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/schedule.png"))); // NOI18N
        jLabel3.setText("     Schedule");
        Menu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 240, 70));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/leave.png"))); // NOI18N
        jLabel4.setText("Log out");
        Menu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 140, 70));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        Menu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1120, 30));

        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 730));

        showList.setBackground(new java.awt.Color(255, 255, 255));
        showList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/liston.png"))); // NOI18N
        showList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showList.setOpaque(true);
        showList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showListMouseExited(evt);
            }
        });
        jPanel1.add(showList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 760));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1180, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int x = 240;
    private void quitListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitListMouseClicked
        if(x == 240){
            Menu.setSize(240, 730);
            Thread th = new Thread(){
               @Override
            public void run(){
                try {
                    for (int i = 240;i >=0; i--){
                        Thread.sleep(1);
                           Menu.setSize(i, 730);
                    }
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, e);}
            }
        };
            th.start();
            x=0;}
       
    }//GEN-LAST:event_quitListMouseClicked

    private void showListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showListMouseClicked
        if(x == 0){
            Menu.show();
            Menu.setSize(x, 730);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i = 0;i <= x;i++){
                            Thread.sleep(1);
                            Menu.setSize(i, 730);
                        }
                    }catch (Exception e){
                        JOptionPane.showMessageDialog(null, e);}
                }
        };
            th.start();
            x = 240;}
    }//GEN-LAST:event_showListMouseClicked

    private void bntexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntexitMouseClicked
       System.exit(0);
    }//GEN-LAST:event_bntexitMouseClicked

// color when mouse on bnt show and quit
    private void quitListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitListMouseEntered
        labelcolor(quitList);
    }//GEN-LAST:event_quitListMouseEntered

    private void showListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showListMouseEntered
        labelcolors(showList);
    }//GEN-LAST:event_showListMouseEntered

    private void quitListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitListMouseExited
        resetlabelcolor(quitList);
    }//GEN-LAST:event_quitListMouseExited

    private void showListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showListMouseExited
        resetlabelcolors(showList);
    }//GEN-LAST:event_showListMouseExited
// make the window move
    int width,height;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        width = evt.getX();
        height = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-width, yy- height);
    }//GEN-LAST:event_jPanel1MouseDragged

// dragg window (move)
    int v,h;
// create function shadow for quit bnt
    private void labelcolor(JLabel label){
        label.setBackground(new java.awt.Color(204,204,204));
    }
    private void resetlabelcolor(JLabel label){
        label.setBackground(new java.awt.Color(0,153,153));
    }
    
// create for show bnt
    private void labelcolors(JLabel label){
        label.setBackground(new java.awt.Color(192,192,192));
    }
    private void resetlabelcolors(JLabel label){
        label.setBackground(new java.awt.Color(255,255,255));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSlide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSlide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSlide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSlide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentSlide().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel bntMinimize;
    private javax.swing.JLabel bntexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel quitList;
    private javax.swing.JLabel showList;
    // End of variables declaration//GEN-END:variables
}
